# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - uname -a
          #- apt-get update -qq
          #- apt-get install software-properties-common -y
          #- echo 'deb http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty main' | tee -a /etc/apt/sources.list.d/cmake.list
          #- apt-get update -qq
          #- apt-get install cmake -y --force-yes
          #- apt-get install -y xorg-dev
          #- apt-get install -y libglu1-mesa-dev    
          #- cmake --version   
          #- python init.py
          #- mkdir build
          #- cd build
          #- cmake ..
          #- cmake --build .
